[MFLOG|0|2023-11-22T16:33:14.066786Z|runtime|4a9472d8-a1b7-46b0-9ee5-076a2a4df052]<flow P2 step start> failed:
[MFLOG|0|2023-11-22T16:33:14.068521Z|runtime|0e610143-8a72-4dd6-a394-ac848d778489]    Internal error
[MFLOG|0|2023-11-22T16:33:14.069224Z|runtime|27e16004-f2ff-4baa-a553-c10c5d5343eb]Traceback (most recent call last):
[MFLOG|0|2023-11-22T16:33:14.069267Z|runtime|0dbf6759-179c-414a-8034-fc807d994af3]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/cli.py", line 1175, in main
[MFLOG|0|2023-11-22T16:33:14.069308Z|runtime|dbab8bbe-417a-4017-81d8-eeb125416e89]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2023-11-22T16:33:14.069339Z|runtime|1fed5432-4f94-42bd-8ffb-2bda847771fb]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2023-11-22T16:33:14.069363Z|runtime|f34ba6ef-6e30-482a-898d-75d1980d3ccd]    return func(args, kwargs)
[MFLOG|0|2023-11-22T16:33:14.093066Z|runtime|e2a97f07-71cc-4b2b-b75d-201059eb68d6]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-11-22T16:33:14.093190Z|runtime|94bc3085-acb3-4fc6-85cc-d0f6b64d1766]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2023-11-22T16:33:14.093232Z|runtime|473b9c72-8070-4ddf-89b3-bc46f0f0eea8]    return self.main(args, kwargs)
[MFLOG|0|2023-11-22T16:33:14.093258Z|runtime|3a0a2bbb-2a2b-4f9f-981a-8f1f555fa069]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-11-22T16:33:14.093282Z|runtime|caf1585a-321d-46a9-83b2-10656e48955d]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2023-11-22T16:33:14.093305Z|runtime|76b6c8c2-b4f1-4f78-b257-cac47279bfe1]    rv = self.invoke(ctx)
[MFLOG|0|2023-11-22T16:33:14.093332Z|runtime|93ae20a4-b4d7-4428-a882-6403a342bb53]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2023-11-22T16:33:14.093354Z|runtime|7e171dd8-a48e-4cfc-aa52-115d974307b4]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2023-11-22T16:33:14.093381Z|runtime|b349e355-f2e0-4b29-ac78-f1c649db97f6]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2023-11-22T16:33:14.093405Z|runtime|9f9276ee-162d-4648-ae84-c180dc8ab0fd]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-11-22T16:33:14.093424Z|runtime|23734326-ad72-45b1-848a-9a6635dc6172]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2023-11-22T16:33:14.093442Z|runtime|9bbb4547-53a4-46bf-99ce-abb667852f31]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2023-11-22T16:33:14.093466Z|runtime|3c57a44a-1801-4835-b1e5-f76a8ea1f553]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-11-22T16:33:14.093487Z|runtime|4ad54fe3-95cf-49c7-9668-dbaf8215b0b3]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2023-11-22T16:33:14.093507Z|runtime|4be1fd60-4342-405d-9416-aa7b6562c7d8]    return callback(args, kwargs)
[MFLOG|0|2023-11-22T16:33:14.093526Z|runtime|6960ddc3-d8e4-4045-94b9-8ee39c4b1597]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-11-22T16:33:14.093544Z|runtime|0f8d73df-1186-4513-8b65-ef9162db81a7]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2023-11-22T16:33:14.093564Z|runtime|faa9d6c3-827a-4708-b3ab-973a9c6418d3]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2023-11-22T16:33:14.093584Z|runtime|66f1e032-e18f-4161-b325-aee37c3a15b6]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-11-22T16:33:14.093603Z|runtime|d94bf215-5ca2-47dc-b1d1-ab63ab2da5f5]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/cli.py", line 582, in step
[MFLOG|0|2023-11-22T16:33:14.093619Z|runtime|ee934bec-50ee-490b-a610-0e034c1ae337]    task.run_step(
[MFLOG|0|2023-11-22T16:33:14.093639Z|runtime|12670df4-33e6-4882-b7ef-217ce794e71b]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/task.py", line 596, in run_step
[MFLOG|0|2023-11-22T16:33:14.093659Z|runtime|b097e4de-e91b-4728-9263-793ef7d3e606]    self._exec_step_function(step_func)
[MFLOG|0|2023-11-22T16:33:14.093676Z|runtime|1cb27027-a9c8-480d-8b7b-803c82d2f388]  File "/Users/fionasy/anaconda3/lib/python3.11/site-packages/metaflow/task.py", line 57, in _exec_step_function
[MFLOG|0|2023-11-22T16:33:14.093695Z|runtime|2cefcf4d-caa2-460a-9c9f-2e2f1d43b63a]    step_function()
[MFLOG|0|2023-11-22T16:33:14.093714Z|runtime|81b46347-442c-4181-984a-29edd0a4f43f]  File "/Users/fionasy/Desktop/VSCODE/P2.py", line 9, in start
[MFLOG|0|2023-11-22T16:33:14.093730Z|runtime|5f60aaaa-4c8b-4a07-b87f-6c51d70c09de]    self.process_training_file('big.txt')
[MFLOG|0|2023-11-22T16:33:14.093750Z|runtime|f37cee73-5ab4-4708-92a6-361784b20f57]  File "/Users/fionasy/Desktop/VSCODE/P2.py", line 16, in process_training_file
[MFLOG|0|2023-11-22T16:33:14.093769Z|runtime|0a0bceb1-e155-4313-8214-2bab1bba371a]    self.WORDS = Counter(words(open(file_path).read()))
[MFLOG|0|2023-11-22T16:33:14.093785Z|runtime|6ca1e418-ec03-422b-a290-9a448574b303]                               ^^^^^^^^^^^^^^^
[MFLOG|0|2023-11-22T16:33:14.093804Z|runtime|5b91b31a-76d1-47c7-bbe2-aa2467262cf9]FileNotFoundError: [Errno 2] No such file or directory: 'big.txt'
[MFLOG|0|2023-11-22T16:33:14.093824Z|runtime|363e1575-e42c-44b6-95f8-1d83df296ba9]
[MFLOG|0|2023-11-22T16:33:14.094180Z|runtime|eb4a7b0b-dc7e-4f6e-bb6e-2a13fec4ea51]Task failed.